# Generated by Django 3.2.8 on 2021-10-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.IntegerField()),
                ('photo_captured', models.TextField()),
                ('photo_edited', models.TextField()),
            ],
        ),
    ]
