# Generated by Django 3.2.8 on 2021-10-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0003_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='emoji',
            name='emoji_id',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
