# Generated by Django 3.2.8 on 2021-10-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0004_emoji_emoji_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.TextField()),
                ('frame_id', models.TextField()),
            ],
        ),
    ]
