# Generated by Django 3.2.8 on 2021-10-23 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0005_frame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emoji',
            name='emoji_id',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='frame',
        ),
    ]
