# Generated by Django 3.2.8 on 2021-10-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0006_auto_20211024_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='frame_id',
        ),
        migrations.AddField(
            model_name='frame',
            name='frame',
            field=models.TextField(default=1),
        ),
    ]
