# Generated by Django 3.2.8 on 2021-10-23 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0007_auto_20211024_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='username',
        ),
    ]
